spring:
  application:
    name: backend

  config:
    import: optional:file:.env[.properties]

  jackson:
    time-zone: Asia/Seoul

--- # 로컬 설정
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mariadb://${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true

    properties:
      hibernate:
        format_sql: false
        show_sql: true

  sql:
    init:
      data-locations: classpath*:db/data.sql
      mode: always
      platform: mariadb

  data:
    redis:
      host: ${LOCAL_REDIS_HOST}
      port: ${LOCAL_REDIS_PORT}

  kafka:
    bootstrap-servers: ${LOCAL_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer:
    consumer:
      group-id: ${LOCAL_KAFKA_CONSUMER_GROUP_ID}

--- # 개발 서버 설정
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mariadb://${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDBDialect

    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer:
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID}
